name: Terraform Plan & Apply

on:
  push:
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:
    inputs:
      apply_confirm:
        description: 'Type YES to confirm terraform apply'
        required: true

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: [self-hosted, baremetal]
    defaults:
      run:
        working-directory: terraform/meatartbot
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply (Manual)
    runs-on: [self-hosted, baremetal]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.apply_confirm == 'YES'
    defaults:
      run:
        working-directory: terraform/meatartbot
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

