name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

jobs:
  terraform-apply:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Terraform Apply
    runs-on: self-hosted
    environment:
      name: production
      # This triggers the manual approval gate

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

