name: Terraform Plan

on:
  push:
    paths:
      - 'terraform/meatartbot/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    paths:
      - 'terraform/meatartbot/**'
      - '.github/workflows/terraform.yml'

jobs:
  terraform:
    name: Terraform Format & Plan
    runs-on: self-hosted
    defaults:
      run:
        working-directory: terraform/meatartbot

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

